name: glade
version: '3.22.1'
summary: GTK+ User Interface Builder
description: |
  Glade is a RAD tool to enable quick & easy development of user interfaces for
  the GTK+ 3 toolkit and the GNOME desktop environment.
  The user interfaces designed in Glade are saved as XML and these can be loaded
  by applications dynamically as needed by using GtkBuilder or used directly to
  define a new GtkWidget derived object class using Gtk+ new template feature.
  By using GtkBuilder, Glade XML files can be used in numerous programming
  languages including C, C++, C#, Vala, Java, Perl, Python,and others.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core18

#icon: share/icons/hicolor/256x256/apps/glade.png
icon: glade.png

slots:
  dbus:
    interface: dbus
    bus: session
    name: org.gnome.Glade

apps:
  glade:
    command: glade
    desktop: share/applications/glade.desktop
    extensions: [ gnome-3-28 ]
    environment:
      GLADE_CATALOG_SEARCH_PATH: "$SNAP/share/glade/catalogs"
      GLADE_MODULE_SEARCH_PATH: "$SNAP/lib/glade/modules"
      GLADE_PIXMAP_DIR: "$SNAP/share/glade/pixmaps"
    plugs:
      - gsettings
      - unity7
      - home
      - removable-media
      - mount-observe
    slots:
      - dbus

parts:
  glade:
    plugin: autotools
    source: https://gitlab.gnome.org/GNOME/glade.git
    source-tag: GLADE_3_22_1
    install-via: prefix
    override-build: |
      # Fix application icon lookup
      sed --in-place 's|^Icon=.*|Icon=\${SNAP}/meta/gui/icon.png|' data/glade.desktop.in.in
      snapcraftctl build
    organize:
      share/locale: usr/share/locale
    build-packages:
      - gnome-common
      - gtk-doc-tools
      - yelp-tools
      - gobject-introspection
      - libgirepository1.0-dev
      - libgtk-3-dev
      - libxml2-dev
      - libwebkit2gtk-4.0-dev
      - python-gi-dev
      - python2.7-dev
    stage-packages:
      - libpython2.7
